### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = 0vtPyGZ-Ybw1gy6PYi8B2isFKxTIJsO_VexdakmRe3v9YYM0sZl3_FROV44Yth23AQI1v0kyBiz9R6KSZ4luWn6lHk6cBOIA

### Send POST request with json body
POST http://localhost:8080/ignoreCsrf
Content-Type: application/json